title: M. Document
description: M. Avatar シリーズのドキュメント
theme: just-the-docs
url: https://mono-meruo.github.io
baseurl: /MDocument.github.io
color_scheme: dark
aux_links: {}
footer_content: Copyright &copy; 2025 M.
github_editme_path: mono-Meruo/MDocument.github.io/edit/main/
